// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2FiVzex2U025EewjB59DZrfpwDlUxCg',
    appId: '1:813775635592:web:357138a58ff9453e06cb3d',
    messagingSenderId: '813775635592',
    projectId: 'fasum-app-1a6d9',
    authDomain: 'fasum-app-1a6d9.firebaseapp.com',
    storageBucket: 'fasum-app-1a6d9.appspot.com',
    measurementId: 'G-D7ZSQ9QMX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA5IMFos4QzTROwW_ih0wtKPCzmfw7Mg0',
    appId: '1:813775635592:android:2618b8bbf007308c06cb3d',
    messagingSenderId: '813775635592',
    projectId: 'fasum-app-1a6d9',
    storageBucket: 'fasum-app-1a6d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDba5hVnRL8OGXePPMrJQE5bkkEIEO1Bo',
    appId: '1:813775635592:ios:b8ea8d595b9ddd2c06cb3d',
    messagingSenderId: '813775635592',
    projectId: 'fasum-app-1a6d9',
    storageBucket: 'fasum-app-1a6d9.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDba5hVnRL8OGXePPMrJQE5bkkEIEO1Bo',
    appId: '1:813775635592:ios:b8ea8d595b9ddd2c06cb3d',
    messagingSenderId: '813775635592',
    projectId: 'fasum-app-1a6d9',
    storageBucket: 'fasum-app-1a6d9.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2FiVzex2U025EewjB59DZrfpwDlUxCg',
    appId: '1:813775635592:web:e9f527ad9774842806cb3d',
    messagingSenderId: '813775635592',
    projectId: 'fasum-app-1a6d9',
    authDomain: 'fasum-app-1a6d9.firebaseapp.com',
    storageBucket: 'fasum-app-1a6d9.appspot.com',
    measurementId: 'G-MGVRCW7LW9',
  );

}